In [6]:
import requests
import torch
import json

In [151]:
headers = {'Content-type': 'application/json',
           'Accept': 'text/plain'}
payload = json.dumps(
    {"img_file": "/images/M2E2/VOA_EN_NW_2016.11.22.3607054/0.h5", "face_index": 0,  "k": 5})
r_fs = requests.get(
    "http://facedb:8000/compare", data=payload, headers=headers)

In [152]:
json.loads(r_fs.text)

{'files': [{'file_name': '/images/M2E2/VOA_EN_NW_2016.11.22.3607054/4.h5',
   'index': 0},
  {'file_name': '/images/M2E2/VOA_EN_NW_2016.12.14.3635692/0.h5', 'index': 0},
  {'file_name': '/images/M2E2/VOA_EN_NW_2016.12.09.3630378/3.h5', 'index': 1},
  {'file_name': '/images/M2E2/VOA_EN_NW_2017.05.17.3854850/1.h5', 'index': 0},
  {'file_name': '/images/M2E2/VOA_EN_NW_2016.02.10.3184933/2.h5', 'index': 0}],
 'similarity': [0.9126031398773193,
  0.8642835021018982,
  0.8624975085258484,
  0.8424574732780457,
  0.8262956738471985]}

In [32]:
m=1
k=512
j=1024
# 2D inputs, same as torch.mm
a = torch.rand(m, k)
b = torch.rand(k, j)
print(a.shape)
print(b.shape)
torch.matmul(a, b)

torch.Size([1, 512])
torch.Size([512, 1024])


tensor([[127.7071, 113.3245, 125.9039,  ..., 128.1579, 119.5202, 129.7647]])

In [111]:
r_fs = requests.get(
    "http://facedb:8000/reverse_map", headers=headers)

In [112]:
json.loads(r_fs.text)

{'/images/M2E2/VOA_EN_NW_2016.07.10.3411182/1.h5': {'0': '0.pt', '1': '1.pt'},
 '/images/M2E2/VOA_EN_NW_2016.07.10.3411182/4.h5': {'0': '2.pt'},
 '/images/M2E2/VOA_EN_NW_2016.07.10.3411182/3.h5': {'0': '3.pt', '1': '4.pt'},
 '/images/M2E2/VOA_EN_NW_2016.07.10.3411182/0.h5': {'0': '5.pt',
  '1': '6.pt',
  '2': '7.pt',
  '3': '8.pt',
  '4': '9.pt',
  '5': '10.pt'},
 '/images/M2E2/VOA_EN_NW_2016.07.10.3411182/2.h5': {'0': '11.pt',
  '1': '12.pt',
  '2': '13.pt',
  '3': '14.pt',
  '4': '15.pt',
  '5': '16.pt',
  '6': '17.pt',
  '7': '18.pt',
  '8': '19.pt',
  '9': '20.pt',
  '10': '21.pt',
  '11': '22.pt',
  '12': '23.pt',
  '13': '24.pt',
  '14': '25.pt',
  '15': '26.pt',
  '16': '27.pt',
  '17': '28.pt',
  '18': '29.pt',
  '19': '30.pt',
  '20': '31.pt',
  '21': '32.pt',
  '22': '33.pt',
  '23': '34.pt',
  '24': '35.pt',
  '25': '36.pt',
  '26': '37.pt',
  '27': '38.pt',
  '28': '39.pt',
  '29': '40.pt',
  '30': '41.pt',
  '31': '42.pt',
  '32': '43.pt',
  '33': '44.pt'},
 '/images/M2E2/

In [100]:
import torch

In [101]:
 x = torch.randn(2, 3)

In [102]:
 y = torch.randn(2, 3)

In [103]:
print(x, y)

tensor([[ 0.9546,  0.2592, -0.8427],
        [-1.4945, -0.7140,  3.5636]]) tensor([[-0.1467, -0.3964, -1.3566],
        [ 0.0296, -2.4540, -0.8877]])


In [106]:
torch.cat((x,y), 0)

tensor([[ 0.9546,  0.2592, -0.8427],
        [-1.4945, -0.7140,  3.5636],
        [-0.1467, -0.3964, -1.3566],
        [ 0.0296, -2.4540, -0.8877]])

In [113]:
r_fs = requests.get(
    "http://facedb:8000/emb", headers=headers)

In [110]:
r_fs

<Response [200]>

In [124]:
temp_list = []
for i in range(100):
    temp_list.append(f"{i}.pt")

In [129]:
import re
def natural_sort(l): 
    convert = lambda text: int(text) if text.isdigit() else text.lower()
    alphanum_key = lambda key: [convert(c) for c in re.split('([0-9]+)', key)]
    return sorted(l, key=alphanum_key)

In [130]:
temp_list.sort()

In [131]:
new_list = natural_sort(temp_list)

In [132]:
new_list

['0.pt',
 '1.pt',
 '2.pt',
 '3.pt',
 '4.pt',
 '5.pt',
 '6.pt',
 '7.pt',
 '8.pt',
 '9.pt',
 '10.pt',
 '11.pt',
 '12.pt',
 '13.pt',
 '14.pt',
 '15.pt',
 '16.pt',
 '17.pt',
 '18.pt',
 '19.pt',
 '20.pt',
 '21.pt',
 '22.pt',
 '23.pt',
 '24.pt',
 '25.pt',
 '26.pt',
 '27.pt',
 '28.pt',
 '29.pt',
 '30.pt',
 '31.pt',
 '32.pt',
 '33.pt',
 '34.pt',
 '35.pt',
 '36.pt',
 '37.pt',
 '38.pt',
 '39.pt',
 '40.pt',
 '41.pt',
 '42.pt',
 '43.pt',
 '44.pt',
 '45.pt',
 '46.pt',
 '47.pt',
 '48.pt',
 '49.pt',
 '50.pt',
 '51.pt',
 '52.pt',
 '53.pt',
 '54.pt',
 '55.pt',
 '56.pt',
 '57.pt',
 '58.pt',
 '59.pt',
 '60.pt',
 '61.pt',
 '62.pt',
 '63.pt',
 '64.pt',
 '65.pt',
 '66.pt',
 '67.pt',
 '68.pt',
 '69.pt',
 '70.pt',
 '71.pt',
 '72.pt',
 '73.pt',
 '74.pt',
 '75.pt',
 '76.pt',
 '77.pt',
 '78.pt',
 '79.pt',
 '80.pt',
 '81.pt',
 '82.pt',
 '83.pt',
 '84.pt',
 '85.pt',
 '86.pt',
 '87.pt',
 '88.pt',
 '89.pt',
 '90.pt',
 '91.pt',
 '92.pt',
 '93.pt',
 '94.pt',
 '95.pt',
 '96.pt',
 '97.pt',
 '98.pt',
 '99.pt']